baseURL = "https://pearg.github.io/pearg_documentation/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "PEARG Documentation"
theme = "hugo-theme-docdock"

[params]
editURL = "https://github.com/pearg/pearg_documentation/edit/master/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = false # default is false
# themeStyle = "theme" # overide base css
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/pearg/pearg_documentation"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-book'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> DocDock Theme"
url = "https://github.com/vjeantet/hugo-theme-docdock"
weight = 30

[[menu.shortcuts]]
name = "<i class='fa fa-globe'></i> PEARG homepage"
url = "https://blogs.unimelb.edu.au/pearg/"
weight = 40
